- services
  - backend
  - ... aws config
  - frontend
  - ... vercel stuff happens here
  - database
  - ... supabase stuff
# this is an adventure for another day, demoed by Jake
# typically this would ive in a /infra folder at top level
# so the project might look like
# /fronted
# /server
# /infra
# (that's it)
